services:
  - type: web
    name: portfolio-api
    env: go
    buildCommand: go build -o portfolio-api
    startCommand: ./portfolio-api
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: PORT
        value: 8080
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_TOKEN_TTL_MINUTES
        value: 720
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false


